workflows:
  ios-simulator:
    name: iOS Simulator - Appetize Testing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Pod install
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Simulator
        script: |
          flutter build ios \
            --debug \
            --simulator \
            --no-codesign

      - name: Zip Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
